name: "DEV DEPLOY"

on:
  push:
    branches:
      - develop

permissions:
  id-token: write
  contents: read

jobs:
  Passo_01:
    uses: ./.github/workflows/Passo_01.yml
  Passo_02:
    uses: ./.github/workflows/Passo_02.yml
  Passo_03:
    uses: ./.github/workflows/Passo_03.yml
    with:
      aws-assume-role-arn: "arn:aws:iam::443164188237:role/github-actions-budelao-pipeline"
      aws-region: "sa-east-1"
  Passo_04:
    uses: ./.github/workflows/Passo_04.yml
    with:
      environment: dev
      aws-region: "sa-east-1"
      aws-statefile-s3-bucket: "budelao-sa-east-1-terraform-statefile-novo"
      aws-lock-dynamodb-table: "budelao-sa-east-1-terraform-lock"        