name: "PROD DEPLOY"

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yml
    with:
      environment: prod
      aws-assume-role-arn: "arn:aws:iam::443164188237:role/github-actions-budelao-pipeline"
      aws-region: "sa-east-1"
      aws-statefile-s3-bucket: "budelao-sa-east-1-terraform-statefile"
      aws-lock-dynamodb-table: "budelao-sa-east-1-terraform-lock"