name: "Terraform Workflow"

on:
  workflow_call:
    inputs:
      aws-assume-role-arn:
        type: string
        required: true
      aws-region:
        type: string
        required: true

jobs:
  config_aws_credentials:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.aws-assume-role-arn }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ inputs.aws-region }}

